### ISSUE TITLE
General site changes

### ISSUE THREAD

**Issue by diaholliday** [City-Bureau/field-guide#52]
- Let's add carrots to the categories in the index to make it more obvious that they are dropdowns

- Change "going public" category to "Frequently Asked Questions"

- Add functionality to checkboxes so that they actually check—could be helpful for Docs using the guide on their phones.

- Automatically close index categories when a new category is selected (i.e. clicking on "resources" will automatically close "on assignment," etc—so that only one category is open at a time).

- Make header larger for mobile view (it looks small now)

**Comment by diaholliday** [comment]
- Decrease width of index text just a bit (the bullet-point are getting cramped in the FAQ section (currently "going public")
![screen shot 2018-11-26 at 1 33 15 pm](https://user-images.githubusercontent.com/4017450/49037470-e4689580-f17f-11e8-8e95-d36cb85a7fa2.png)

**Comment by pjsier** [comment]
All of these should be resolved now
